In [32]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
dow_jones = pd.read_csv(r"C:\Users\victo\Desktop\datasets\Dow Jones Index data\dow_jones_index.data")

dow_jones = dow_jones.dropna()
dow_jones = dow_jones.drop_duplicates()
dow_jones.head()

# Training data vs Test data:
# In (Brown, Pelosi & Dirska, 2013) we used quarter 1 (Jan-Mar) data for training and quarter 2 (Apr-Jun) data for testing.

,quarter,stock,date,open,high,low,close,volume,percent_change_price,percent_change_volume_over_last_wk,previous_weeks_volume,next_weeks_open,next_weeks_close,percent_change_next_weeks_price,days_to_next_dividend,percent_return_next_dividend
1,1,AA,1/14/2011,$16.71,$16.71,$15.64,$15.97,242963398,-4.428490,1.380223,239655616.0,$16.19,$15.79,-2.470660,19,0.187852
2,1,AA,1/21/2011,$16.19,$16.38,$15.60,$15.79,138428495,-2.470660,-43.024959,242963398.0,$15.87,$16.13,1.638310,12,0.189994
3,1,AA,1/28/2011,$15.87,$16.63,$15.82,$16.13,151379173,1.638310,9.355500,138428495.0,$16.18,$17.14,5.933250,5,0.185989
4,1,AA,2/4/2011,$16.18,$17.39,$16.18,$17.14,154387761,5.933250,1.987452,151379173.0,$17.33,$17.37,0.230814,97,0.175029
5,1,AA,2/11/2011,$17.33,$17.48,$16.97,$17.37,114691279,0.230814,-25.712195,154387761.0,$17.39,$17.28,-0.632547,90,0.172712

In [44]:
dow_jones.info()

<class 'pandas.core.frame.DataFrame'>
Index: 720 entries, 1 to 749
Data columns (total 16 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   quarter                             720 non-null    int64
 1   stock                               720 non-null    object
 2   date                                720 non-null    object
 3   open                                720 non-null    object
 4   high                                720 non-null    object
 5   low                                 720 non-null    object
 6   close                               720 non-null    object
 7   volume                              720 non-null    int64
 8   percent_change_price                720 non-null    float64
 9   percent_change_volume_over_last_wk  720 non-null    float64
 10  previous_weeks_volume               720 non-null    float64
 11  next_weeks_open                     720 non-null    object
 12  next_weeks_close                    720 non-null    object
 13  percent_change_next_weeks_price     720 non-null    float64
 14  days_to_next_dividend               720 non-null    int64
 15  percent_return_next_dividend        720 non-null    float64
dtypes: float64(5), int64(3), object(8)
memory usage: 95.6+ KB

In [ ]:
plt.figure(figsize=(8, 6))
sns.heatmap(corr_matr, annot=True, cmap='coolwarm', linewidths=0.5)
plt.title('correlation heatmap of dow jones features')
plt.show()